### ISSUE TITLE
Question about amusement park app

### ISSUE THREAD

**Issue by bfellerath** [bfellerath/RESTaurant#1]
I was just trying to use the amusement park app to see its functionality but I wasn't able to get it running, I'm wondering if I have to redo all the data migrations. I probably do but I wanted to make sure that was why before I went and did it.

Bryan

**Comment by amadden80** [comment]
To start the application, I trust you would need to:

`bundle`
`bundle exec rake db:create`
`bundle exec rake db:migrate`
`bundle exec rackup`

Does that work?   You need your machine to have all the setting up that my machine has.

**Comment by bfellerath** [comment]
It did work and then I clicked a submit button for thrills I think and it is giving me an error. I can probably figure it out. I'm getting an error just going to localhost:9292

**Comment by amadden80** [comment]
Alright.  Reopen the issue if the issues doesn't get solved.
