### ISSUE TITLE
Trying to update food_items, having trouble with the route. 

### ISSUE THREAD

**Issue by bfellerath** [bfellerath/RESTaurant#3]
Writing the following code:

```
    #--- UPDATE FOOD ITEMS: update --
  put '/:id' do
    food_item = FoodItem.find(params[:id])
    food_item.update(params["name"])
    redirect "/food_items/#{food_item.id}"

  end
```

Getting this error: When assigning attributes, you must pass a hash as an argument.

**Comment by emilylordahl** [comment]
Taking a look now. Can you push so I can check out your edit food items view?

**Comment by emilylordahl** [comment]
But at first glance, I believe the params with which you are trying to update are a little off. Do you want to update the params for the food_item?

**Comment by emilylordahl** [comment]
...like so:

`food_item.update(params[:food_item])`

**Comment by bfellerath** [comment]
I have it working now

**Comment by emilylordahl** [comment]
:ok_hand::ok_hand::ok_hand::ok_hand::ok_hand::ok_hand:
