### ISSUE TITLE
  #- DESTROY ITEM_ORDER: destroy -

### ISSUE THREAD

**Issue by bfellerath** [bfellerath/RESTaurant#4]
Here is what I have so far:

As a user I want to be able to delete orders after the party has paid and left the restaurant so I don't have a whole bunch of old, irrelevant item_orders polluting my app.

```
delete '/:id' do
    ItemOrder.delete(params[:id])
    redirect '/item_orders'
  end
```

and here is the form:

```
<form action="/item_orders/<% @item_order.id %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="delete">

</form>
```

The error message I get is:

Also I notice that in the amusement parks app, Andrew has a more involved destroy function than in the cheese app (which is what I was looking at first). It is my understanding that I might need this because I may need to not only delete the item order, but the party as well. That code is:

```
  delete '/:id' do
    thrillseeker = ThrillSeeker.find(params[:id])
    thrillseeker.thrills.each {|thrill| thrill.delete }
    thrillseeker.delete()
    redirect '/'
  end
```

Also in general I wanted to get some feedback about where I am in my project. I know it said today we should have full CRUD. I don't. I think Destroy is the last thing I need but then I need to give destroy and update to more things probably. Also I feel like maybe I need to look at the amusement parks app more to see how it is working, haven't really had a chance to use that yet.

**Comment by bfellerath** [comment]
I forgot to put the error in there
hold on I will get it

**Comment by bfellerath** [comment]
sinatra is telling me to try:

```
 delete '/' do
    "Hello World"
  end
```

**Comment by rapala61** [comment]
in person
