### ISSUE TITLE
CSS SKELETON Is breaking on my edit.erb

### ISSUE THREAD

**Issue by bfellerath** [bfellerath/RESTaurant#5]
When I am redirected to my edit.erb in either food_items or item_orders I get a page that is unstyled. It seems like it is not going through my layout. 

Right now I am going to git push origin master so you can see what I am talking about if you want to.

**Comment by rapala61** [comment]
Assigned to Andrew, im out on a Dr. Appt

**Comment by bfellerath** [comment]
This might be kind of an unusual problem. People seem intrigued by it.

**Comment by amadden80** [comment]
_in person_

Changed  `css/styles.css` to `/css/styles.css`
